### ISSUE TITLE
Some outdated dependencies in .spec file

### ISSUE THREAD

**Issue by past-due** [OpenMandrivaAssociation/warzone2100#6]
From a quick (non-exhaustive) review of the .spec file, I noticed references to the following packages that are no longer Warzone 2100 dependencies:
- Qt5*
- glew
- quesoglc

(Hopefully removing those will help speed up packaging.) 👍

**Comment by AngryPenguinPL** [comment]
Thanks for report.
I waited to remove some unnecessary buildrequires for a new release that has just arrived. I updated the package to 4.2.4 and removed some redundant br.
It should be fine now. 
https://github.com/OpenMandrivaAssociation/warzone2100/pull/7
